### ISSUE TITLE
ToDo / Ideas / v1.0.1

### ISSUE THREAD

**Issue by RusJJ** [RusJJ/AndroidModLoader#1]
Leave your ideas below!

ToDo:
- IL2CPP
- Fake app pak name/ver + api

**Comment by ROCKSTARMODSZ** [comment]
The Bullet Physics Mod For Android

**Comment by RusJJ** [comment]
Let me think... Uhm... No

**Comment by RusJJ** [comment]
- Vtable hooks

**Comment by RusJJ** [comment]
- HasExtStorageAccess()
- Ext. mod loading
- Bypass namespace?
