### ISSUE TITLE
Compilation instructions

### ISSUE THREAD

**Issue by strikersix23** [RusJJ/AndroidModLoader#11]
Missing libraries make it hard for me to compile as there is no indication as to the proper versions or where to get i am able to get arm patch, have no idea about the rest. maybe add a download script?

**Comment by RusJJ** [comment]
1. You need to put xDL files into the folder xDL
2. You need libCURL compiled with WolfSSL because it is lightweght and opensource. And put them into needed folder.
If i miss something, just check this file: https://github.com/RusJJ/AndroidModLoader/blob/main/Android.mk

**Comment by strikersix23** [comment]
Yes but where is xDl from

**Comment by strikersix23** [comment]
That's what i am missing

**Comment by RusJJ** [comment]
> That's what i am missing

https://github.com/hexhacking/xDL

**Comment by strikersix23** [comment]
Im getting a missing header 

GTASA_structs.h 

Is that a hidden header?

**Comment by RusJJ** [comment]
How is that related to AndroidModLoader?

**Comment by strikersix23** [comment]
Its not directly i looked through the whole organization for this header and find 12 references but no headers, since it isn't here and multiple mods reference it i figured it might be missing from the mod folder for aml

**Comment by RusJJ** [comment]
Now automatically compilable (even though cURL, wolfSSL and libz arent automatically compiled now because they are kinda *ugh* to build)
