### ISSUE TITLE
How do I read and edit an Android game data file name (resconf.VBlrpIFB5troECtzJzXQxbO0FdY~3D)?

### ISSUE THREAD

**Issue by Shaanusmani** [RusJJ/AndroidModLoader#19]

**Comment by RusJJ** [comment]
No clue where you found such a weird file.

**Comment by Shaanusmani** [comment]
/storage/emulated/0/Android/data/com.dts.freefiremax/files/contentcache/Compulsory/android/gameassetbundles/config/resconf.VBlrpIFB5troECtzJzXQxbO0FdY~3D

I think now you can understand its a garena free fire max config file

**Comment by RusJJ** [comment]
This is not related to the AndroidModLoader..

**Comment by Shaanusmani** [comment]
Ok
